version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    command:
      - /bin/bash
      - -lc
      - rm -f Gemfile.lock && exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace --force_polling
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
